import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowLeft, ArrowRight, BookOpen, Check, ChevronDown, CircleHelp, Clock3, Eye, FileText, Fingerprint, Flame, FolderOpen, LockKeyhole, Map, MessageCircle, Moon, NotebookTabs, Search, Settings2, Shield, Snowflake, Sparkles, X } from 'lucide-react';
import './style.css';

const clues = [
  { id:'C1', name:'后脑钝伤', desc:'头皮下有明显血肿。它不像心梗的征象，更像一次从背后而来的重击。', place:'书房 · 尸体', icon:'✣', key:true },
  { id:'C2', name:'未开封的救心药', desc:'封膜完整，药片数与医嘱一致。一个正在心梗发作的人，不会把药瓶拧紧放好。', place:'书房 · 书桌', icon:'◉', key:true },
  { id:'C3', name:'插销上的细线勒痕', desc:'横插销手柄留有一道新鲜细痕。光线掠过时，纤维边缘泛着微弱的冷光。', place:'书房 · 房门', icon:'╱', key:true },
  { id:'C4', name:'拨火棍残留', desc:'棍头缝隙有暗褐色残留，棍身微弯，表面留有新近擦拭痕。', place:'书房 · 壁炉', icon:'⌁', key:true },
  { id:'C5', name:'门底倒毛的地毯', desc:'地毯纤维朝门外倒伏，门底约 8 毫米的缝隙恰好能通过细线。', place:'书房 · 房门', icon:'≈', key:true },
  { id:'C6', name:'21:16 家族群语音', desc:'陆伯年的声音清楚地留在群聊里。发出时，他还活着。', place:'书房 · 手机', icon:'◖', key:true },
  { id:'C7', name:'降雪与积雪记录', desc:'暴雪 19:40 开始、22:10 停止。21:24 之后的降雪足以填平庭院脚印。', place:'东回廊 · 花坛', icon:'❄', key:true },
  { id:'C8', name:'短缺的尼龙鱼线', desc:'线卷标称 50 米，实测只有 46.8 米；断头新鲜，短缺的 3.2 米去向不明。', place:'高坤房间 · 储物柜', icon:'⌇', key:true },
  { id:'C9', name:'鞋底紫杉针叶', desc:'高坤鞋底卡槽里有紫杉针叶，裤脚沾着雪水盐渍。厨房路线没有紫杉。', place:'人物检视 · 高坤', icon:'✳', key:true },
  { id:'C10', name:'司机的不在场证词', desc:'司机确认陆之遥 21:05 后一直在客厅喝酒，没有离开。', place:'客厅 · 司机', icon:'▤' },
  { id:'C11', name:'影音室保姆证词', desc:'21:17 起，苏曼与顾明远一直在影音室。暧昧关系是真的，行凶机会却不存在。', place:'客厅 · 保姆', icon:'▤' },
  { id:'C12', name:'高翔留下的遗信', desc:'高坤的儿子高翔写下陆伯年如何把工程事故推给自己、毁掉他一生。', place:'高坤房间 · 木箱', icon:'✉' },
];
const deductions = [
  { id:'D1', title:'心梗是假象', body:'陆伯年死于后脑钝击。药瓶未开、拨火棍留有擦拭痕，死亡被伪装成心梗。', need:['C1','C2','C4'] },
  { id:'D2', title:'死亡窗口', body:'最后的语音证明陆伯年 21:16 仍活着；死亡发生在降雪停歇前。', need:['C6','C7'] },
  { id:'D3', title:'门外的密室机关', body:'鱼线穿过门底缝隙，门外拉动横插销，再将鱼线抽回，形成机械密室。', need:['C3','C5','C8'] },
  { id:'D4', title:'被雪抹去的脚印', body:'凶手从东回廊经过紫杉花坛离开，脚印被持续降雪覆盖。', need:['C7','C9'] },
  { id:'D5', title:'唯一满足全部条件的人', body:'高坤同时拥有作案时间、鱼线工具、紫杉路线痕迹，以及替儿子复仇的动机。', need:['D1','D2','D3','D4','C12'] },
];
const suspects = [
  { name:'高坤', role:'庄园管家 · 58 岁', line:'老爷是老毛病犯了。21 点后我一直在厨房。', truth:'你说自己没有离开厨房，可鞋底的紫杉针叶不会替你撒谎。那片花坛，离厨房只有一条回廊。' },
  { name:'陆之遥', role:'死者侄子 · 28 岁', line:'我们是吵过架。但 21:05 之后我就没进过书房。', truth:'司机的证词与客厅里那杯酒的时间都对得上。欠债让你看起来可疑，却没有给你作案的机会。' },
  { name:'苏曼', role:'死者妻子 · 32 岁', line:'药是我和顾医生一起送的。之后我去了影音室。', truth:'她隐瞒了与顾明远的关系，却没有隐瞒能杀人的事。21:16 的语音和保姆证词给了她不在场证明。' },
  { name:'顾明远', role:'家庭医生 · 45 岁', line:'一开始我确实以为是心梗，但我送药时他还好好的。', truth:'你的判断被现场误导了。21:16 的语音证明，送药之后陆伯年仍然活着。' },
];
const questions = ['陆伯年的真正死因？','死亡时间窗口？','密室是如何形成的？','凶手如何离开而不留下脚印？','谁同时拥有动机、工具与时间？'];
const solution = ['送热可可进入书房','拨火棍击打后脑','摆出伏案睡姿，放置药瓶','鱼线套住插销，出门拉线锁门','踏东回廊返回，脚印被新雪覆盖'];
const hotspots = {
  '书房': [ ['尸体后脑','C1','头发下面藏着不属于疾病的痕迹。'], ['救心药瓶','C2','瓶口封膜完好，药片一粒没少。'], ['横插销','C3','内侧横插销上有一道纤细的勒痕。'], ['壁炉拨火棍','C4','棍头的暗褐色残留没能被擦干净。'], ['门底地毯','C5','纤维逆着门的方向倒伏，门缝足够细线通过。'], ['书桌手机','C6','群聊语音时间：21:16。'] ],
  '东回廊': [ ['紫杉花坛','C7','雪层记录与花坛边缘的足迹，构成一段被覆盖的离开路线。'] ],
  '厨房与客厅': [ ['司机的证词','C10','陆之遥离开书房后，一直在客厅。'], ['保姆的证词','C11','21:17 之后，苏曼与顾医生一直在影音室。'] ],
  '高坤房间': [ ['储物柜','C8','鱼线卷少了 3.2 米，断头是新的。'], ['旧木箱','C12','一封写给父亲的遗信，落款是高翔。'] ],
  '人物检视': [ ['高坤的鞋与裤脚','C9','鞋槽里的紫杉针叶，来自厨房路线之外。'] ],
};
const chapters = [
  {n:'01', title:'雪夜密室', setting:'暴风雪山庄', difficulty:'★', synopsis:'一扇从内部锁上的书房门，一瓶没有打开的救心药。暴雪封住了所有出口。', status:'可调查'},
  {n:'02', title:'浮床', setting:'别墅轰趴', difficulty:'★★', synopsis:'泳池边一场看似意外的溺亡，浮床在夜色中缓慢倾斜。', status:'案卷封存'},
  {n:'03', title:'二号麦', setting:'KTV 聚会', difficulty:'★★★', synopsis:'一支麦克风，一次突然断电，一场朝向特定座位的毒杀。', status:'案卷封存'},
  {n:'04', title:'吹灭蜡烛之后', setting:'生日宴', difficulty:'★★★★', synopsis:'九十秒黑暗。一声杯碎之后，主桌的寿星倒在烛光熄灭处。', status:'案卷封存'},
];

function App(){
  const [phase,setPhase]=useState('cabinet'); const [scene,setScene]=useState('书房'); const [found,setFound]=useState(()=>JSON.parse(localStorage.getItem('mist-found')||'[]')); const [made,setMade]=useState(()=>JSON.parse(localStorage.getItem('mist-made')||'[]'));
  const [cred,setCred]=useState(()=>Number(localStorage.getItem('mist-cred')||100)); const [intuition,setIntuition]=useState(3); const [modal,setModal]=useState(''); const [selected,setSelected]=useState(null); const [toast,setToast]=useState(''); const [tab,setTab]=useState('证物'); const [npc,setNpc]=useState(0); const [challenged,setChallenged]=useState(false); const [challengeText,setChallengeText]=useState(''); const [order,setOrder]=useState([]); const [wrong,setWrong]=useState(0); const [testimony,setTestimony]=useState(0); const [caseDone,setCaseDone]=useState(localStorage.getItem('mist-done')||''); const [zoom,setZoom]=useState(1);
  const [settings,setSettings]=useState(()=>JSON.parse(localStorage.getItem('mist-settings')||'{"highlight":true,"largeText":false}'));
  useEffect(()=>{localStorage.setItem('mist-found',JSON.stringify(found));},[found]); useEffect(()=>{localStorage.setItem('mist-made',JSON.stringify(made));},[made]); useEffect(()=>{localStorage.setItem('mist-cred',String(cred));},[cred]); useEffect(()=>{localStorage.setItem('mist-settings',JSON.stringify(settings));document.documentElement.classList.toggle('large-text',settings.largeText);},[settings]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t);}},[toast]);
  const clueById=id=>[...clues,...deductions].find(x=>x.id===id); const unlocked=found.length; const currentHotspots=hotspots[scene]||[]; const doneScene=currentHotspots.filter(h=>found.includes(h[1])).length;
  const solved=useMemo(()=>new Set(made),[made]); const allReady=deductions.every(d=>solved.has(d.id))&&clues.filter(c=>c.key).every(c=>found.includes(c.id));
  function acquire(id){if(found.includes(id)){setSelected(clueById(id));setModal('inspect');return;}setFound(v=>[...v,id]);const c=clueById(id);setToast(`新线索已归档 · ${c?.name}`);setSelected(clueById(id));setModal('inspect');}
  function buildDeduction(d){if(solved.has(d.id))return;const valid=d.need.every(id=>found.includes(id)||solved.has(id));if(!valid){setCred(v=>Math.max(0,v-2));setToast('线索之间还缺少关键一环，可信度 −2');return;}setMade(v=>[...v,d.id]);setToast(`推论成立 · ${d.title}`);}
  function cross(){if(npc===0){if(found.includes('C9')){setCred(Math.max(0,cred));setChallenged(false);setChallengeText('');setToast('高坤的证词出现裂痕。鞋底的紫杉针叶与短缺的鱼线，都指向书房外的路线。');}else{setCred(v=>Math.max(0,v-10));setChallengeText('需要一件能证明你离开厨房的实物证据。');setToast('证据不足，对峙失效 · 可信度 −10');}}else if(npc===3){if(found.includes('C6')){setToast('顾明远沉默下来，承认 21:16 后没有再见过陆伯年。');setFound(v=>v.includes('C11')?v:[...v,'C11']);setChallenged(false);}else{setCred(v=>Math.max(0,v-10));setToast('这条证据无法证明送药后的时间 · 可信度 −10');}}else{setCred(v=>Math.max(0,v-10));setToast('这条证据与当前证词无关 · 可信度 −10');}}
  function startCase(){setPhase('intro');setScene('书房');setModal('');}
  function finish(){localStorage.setItem('mist-done','A');setCaseDone('A');setPhase('ending');}
  function clickAct(act){if(act==='clues'){setTab('证物');setModal('file');} if(act==='deductions'){setModal('board');} if(act==='people'){setTab('人物');setModal('file');} if(act==='interview'){setModal('interview');} if(act==='case'){setPhase('closing');setModal('');} if(act==='settings')setModal('settings');}

  return <main className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setPhase('cabinet')}><span className="brand-mark"><Fingerprint size={22}/></span><span><b>迷雾案卷</b><small>CASE FILES IN THE MIST</small></span></button><div className="top-center"><span className="live-dot"/> 鹿鸣山庄 · 12 月 24 日 <i>/</i> 22:25 <Snowflake size={15}/></div><div className="top-actions"><button className="icon-btn" title="侦探手册" onClick={()=>clickAct('clues')}><NotebookTabs size={18}/></button><button className="icon-btn" title="设置" onClick={()=>clickAct('settings')}><Settings2 size={18}/></button><div className="cred-pill"><Shield size={15}/><span>可信度</span><b>{cred}</b><span className="cred-track"><i style={{width:`${cred}%`}}/></span></div><button className="portrait">林</button></div></header>
    {phase==='cabinet'&&<section className="cabinet-view"><div className="cabinet-intro"><div className="eyebrow"><span/> PRIVATE INVESTIGATION ARCHIVE <span/></div><h1>所有人都在说谎。<br/><em>现场不会。</em></h1><p>独立案件档案 · 逐卷解封</p><div className="case-index"><b>档案总览</b><span>04 CASE FILES</span><span className="index-line"/><small>推荐调查顺序 01 → 04</small></div></div><div className="case-grid">{chapters.map((c,i)=><button className={`case-card ${i===0?'available':'sealed'}`} key={c.n} onClick={()=>i===0?startCase():setToast('这份案卷尚未完成归档。')}><span className="case-card-top"><span>FILE / {c.n}</span>{i===0?<span className="available-tag"><i/> {caseDone ? '已结案 · '+caseDone : '可调查'}</span>:<LockKeyhole size={15}/>}</span><div className={`case-art art-${i+1}`}><div className="art-snow"/><div className="art-symbol">{['❄','⌁','◖','✣'][i]}</div><div className="art-number">{c.n}</div><div className="art-caption">{c.setting}<span> · {c.difficulty}</span></div></div><div className="case-card-copy"><small>CASE {c.n}　 /　 {c.setting}</small><h2>{c.title}</h2><p>{c.synopsis}</p><span className="case-cta">{i===0 ? '开启调查' : caseDone ? '重访案卷' : '开启调查'} <ArrowRight size={15}/></span></div></button>)}</div><footer className="cabinet-footer"><span>AN ORIGINAL DETECTIVE STORY</span><span>离线档案已启用 · 进度自动保存</span><span>林彻 · 私家侦探</span></footer></section>}

    {phase==='intro'&&<section className="intro-screen"><div className="intro-art"><div className="storm-lines"/><div className="window-glow"/><div className="desk"/><div className="body-shape"/><div className="intro-vignette"/></div><div className="intro-copy"><div className="eyebrow"><span/> CASE 01 · 序章 <span/></div><h1>雪夜密室</h1><p className="intro-place">北方山区 · 鹿鸣山庄 · 22:25</p><div className="intro-rule"/><p>暴雪封山。书房的门从里面锁住，陆伯年伏在桌前，手边倒着一瓶救心药。</p><p className="intro-quote">“老爷是老毛病犯了。”<br/><span>管家高坤这样说。</span></p><p>而家庭医生顾明远，也点了点头。</p><button className="primary-btn" onClick={()=>setPhase('investigate')}>进入现场 <ArrowRight size={16}/></button><button className="text-btn" onClick={()=>setPhase('cabinet')}><ArrowLeft size={14}/> 返回案卷柜</button></div></section>}

    {phase==='investigate'&&<section className="investigation"><div className={`scene-art scene-${scene}`}><div className="scene-backdrop"><div className="scene-window"><span/><i/></div><div className="scene-shelf"><i/><i/><i/></div><div className="scene-fire"><Flame size={40}/><i/></div><div className="scene-desk"><div className="scene-corpse"><span/></div><div className="scene-bottle"/></div><div className="scene-door"><i/></div><div className="scene-lamp"/><div className="scene-prop prop-a"/><div className="scene-prop prop-b"/><div className="dust dust-a"/><div className="dust dust-b"/></div><div className="scene-shade"/><div className="scene-meta"><span>现场勘查　/　{scene}</span><span>已归档 {found.filter(id=>clues.find(c=>c.id===id)?.key).length} / 9 条关键线索</span></div><div className="hotspot-layer">{currentHotspots.map((h,i)=><button key={h[1]} className={`hotspot hot-${i+1} ${found.includes(h[1])?'found':''} ${settings.highlight&&!found.includes(h[1])?'glow':''}`} onClick={()=>acquire(h[1])}><span>{found.includes(h[1])?<Check size={13}/>:<Search size={13}/>}</span><b>{h[0]}</b></button>)}</div></div>
      <div className="investigate-panel"><div className="scene-selector">{Object.keys(hotspots).map((s,i)=><button className={scene===s?'active':''} key={s} onClick={()=>setScene(s)}><span>0{i+1}</span>{s}{scene===s&&<i/>}</button>)}</div><div className="scene-progress"><span>本节点调查完成</span><b>{doneScene} / {currentHotspots.length}</b><div className="progress-track"><i style={{width:`${currentHotspots.length?doneScene/currentHotspots.length*100:0}%`}}/></div></div><div className="detective-voice"><span className="voice-mark">林</span><p>{found.length<2?'大家都在看他的胸口。可后脑这缕头发，塌得不太自然。':scene==='书房'?'现场不会替自己解释。把每一处痕迹都留下来。':scene==='高坤房间'?'鱼线的断口很新。有人带走了一段，也带走了锁门的办法。':'每条证词都可以回到现场，找到自己的位置。'}</p></div><div className="tool-row"><button onClick={()=>clickAct('clues')}><NotebookTabs size={17}/><span>侦探手册</span><i>{found.length}</i></button><button onClick={()=>clickAct('deductions')}><Fingerprint size={17}/><span>推理板</span><i>{made.length}/5</i></button><button onClick={()=>clickAct('interview')}><MessageCircle size={17}/><span>询问</span></button><button disabled={!allReady} className="close-btn" onClick={()=>clickAct('case')}>结案陈词 <ArrowRight size={15}/></button></div></div></section>}

    {phase==='closing'&&<section className="closing-view"><div className="closing-head"><button className="back-link" onClick={()=>setPhase('investigate')}><ArrowLeft size={15}/> 返回调查</button><span className="eyebrow"><span/> FINAL DEDUCTION</span><h1>让证据，<em>指向唯一的答案。</em></h1><p>你拼出的五条推论，已足以还原这场雪夜里的密室。</p></div><div className="closing-grid"><div className="closing-step"><div className="step-top"><span>01 / 指认</span><span>WHO DID IT</span></div><h2>谁有机会离开厨房？</h2><div className="suspect-list">{suspects.map((s,i)=><button key={s.name} onClick={()=>{if(i===0){setTestimony(1);setToast('高坤的目光移向桌面。他仍然否认。');}else{setCred(v=>Math.max(0,v-30));setToast(`${s.name} 当场反驳了你的指认 · 可信度 −30`);}}} className={testimony&&i===0?'suspect-correct':''}><span className="suspect-initial">{s.name[0]}</span><span><b>{s.name}</b><small>{s.role}</small></span><ArrowRight size={15}/></button>)}</div></div><div className="closing-step"><div className="step-top"><span>02 / 还原</span><span>RECONSTRUCT</span></div><h2>排列作案环节</h2><p className="step-desc">选择下方卡片，将它们依次放入时间线。</p><div className="order-slots">{Array.from({length:5},(_,i)=><button className={order[i]?'filled':''} key={i} onClick={()=>setOrder(v=>v.filter((_,j)=>j!==i))}><span>0{i+1}</span><b>{order[i]||'选择一个作案环节'}</b>{order[i]?<X size={14}/>:<ChevronDown size={14}/>}</button>)}</div><div className="order-options">{solution.filter(x=>!order.includes(x)).map((x,i)=><button key={x} onClick={()=>setOrder(v=>[...v,x])}><span>{String.fromCharCode(65+i)}</span>{x}<ArrowRight size={13}/></button>)}</div><button className="primary-btn verify-btn" disabled={order.length<5} onClick={()=>{const ok=order.every((x,i)=>x===solution[i]);if(ok){setTestimony(2);setToast('五个环节严丝合缝。接下来，用证据回应他的三句狡辩。');}else{setWrong(v=>v+1);setCred(v=>Math.max(0,v-25));setToast('时间线有一处不成立，线索提醒：拨火棍在摆放尸体之前使用。');setOrder([]);}}}>核对时间线 <Check size={15}/></button></div></div>
      {testimony>=2&&<div className="cross-exam"><div><span className="eyebrow"><span/> 03 / 证据质证</span><h2>三句狡辩，三把钥匙</h2></div>{[['“老爷是心梗。”',['C1','C2']],['“鱼线只是白天清理冰溜用的。”',['C8','C3']],['“我没离开过厨房。”',['C9','C7']]].map((q,i)=><button key={q[0]} disabled={testimony>2+i} onClick={()=>{if(found.includes(q[1][0])&&found.includes(q[1][1])){setTestimony(v=>v+1);setToast(`证据成立 · 质证 ${i+1}/3`);if(i===2)setTimeout(finish,900);}else setToast('还缺少这一处质证需要的证据。');}}><span>0{i+1}</span><b>{q[0]}</b><small>{q[1].map(x=>clueById(x)?.name).join(' + ')}</small>{testimony>2+i?<Check size={16}/>:<ArrowRight size={15}/>}</button>)}</div>}
      <div className="closing-foot"><span><Shield size={14}/> 可信度 {cred}</span><span>线索 {found.filter(id=>clues.find(c=>c.id===id)?.key).length}/9　·　推论 {made.length}/5</span></div></section>}

    {phase==='ending'&&<section className="ending-view"><div className="ending-mark"><Check size={38}/></div><div className="eyebrow"><span/> CASE CLOSED · 01</div><h1>雪夜有了答案。</h1><p>高坤低下头。壁炉里的最后一点火光，映着他攥紧的手。</p><blockquote>“八年前，他毁了高翔的一生。我留在这里，只为等一个能让他偿还的夜晚。”</blockquote><div className="ending-summary"><span><b>{found.filter(id=>clues.find(c=>c.id===id)?.key).length}/9</b><small>关键线索</small></span><span><b>{made.length}/5</b><small>关键推论</small></span><span><b>{Math.max(0,100-cred)}</b><small>可信度损耗</small></span><span><b>A</b><small>案卷评级</small></span></div><div className="replay-card"><span>真相回放</span><p>鱼线从门底一寸寸抽回。雪花落下，将回廊上的脚印逐渐填平。</p></div><button className="primary-btn" onClick={()=>setPhase('cabinet')}>归档并返回案卷柜 <ArrowRight size={16}/></button></section>}

    {modal==='inspect'&&selected&&<div className="overlay" onClick={()=>setModal('')}><section className="inspect-modal" onClick={e=>e.stopPropagation()}><button className="close-x" onClick={()=>setModal('')}><X size={18}/></button><div className="inspect-visual" style={{'--zoom':zoom}}><div className="evidence-glyph">{selected.icon||'✣'}</div><span className="scan-ring"/><span className="scan-cross">+</span><small>{selected.id} / EVIDENCE DETAIL</small></div><div className="inspect-copy"><span className="eyebrow"><span/> {selected.id} · {selected.key?'关键线索':'调查记录'}</span><h2>{selected.name}</h2><p>{selected.desc}</p><div className="evidence-source"><Map size={15}/>{selected.place||'侦探推论'}</div><div className="inspect-controls"><button onClick={()=>setZoom(v=>Math.min(1.4,v+.1))}><Search size={14}/> 放大</button><button onClick={()=>setZoom(v=>Math.max(.7,v-.1))}><Search size={14}/> 缩小</button><button onClick={()=>setModal('compare')}><Sparkles size={14}/> 比对线索</button></div><button className="primary-btn" onClick={()=>{setModal('');setZoom(1);}}>归入侦探手册 <Check size={15}/></button></div></section></div>}

    {modal==='file'&&<div className="overlay" onClick={()=>setModal('')}><section className="file-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow"><span/> DETECTIVE'S CASEBOOK</span><h2>侦探手册</h2></div><button className="close-x" onClick={()=>setModal('')}><X size={18}/></button></div><div className="file-tabs">{['证物','人物','时间线','证词','推论'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="file-content">{tab==='证物'&&<div className="clue-list">{clues.filter(c=>found.includes(c.id)).map(c=><button onClick={()=>{setSelected(c);setModal('inspect')}} key={c.id}><span>{c.icon}</span><div><b>{c.name}</b><small>{c.id}　·　{c.place}</small></div>{c.key&&<i>关键</i>}<ArrowRight size={14}/></button>)}{!found.length&&<p className="empty">尚无归档线索。现场的每一处痕迹，都值得再看一眼。</p>}</div>}{tab==='人物'&&<div className="people-list">{suspects.map((s,i)=><button key={s.name} onClick={()=>{setNpc(i);setModal('interview')}}><span className="suspect-initial">{s.name[0]}</span><div><b>{s.name}</b><small>{s.role}</small></div><span className="person-state">{i===0&&found.includes('C9')?'证词存疑':'待询问'}</span><ArrowRight size={14}/></button>)}</div>}{tab==='时间线'&&<div className="timeline">{[['19:40','暴雪封住山路'],['21:00','陆之遥进入书房'],['21:15','苏曼与顾明远送药'],['21:16','家族群语音发出'],['21:17','苏曼与顾明远进入影音室'],['21:18','有人端着热可可走向书房'],['21:24','东回廊的脚印开始被新雪覆盖'],['22:10','降雪停止'],['22:25','书房门被撞开']].map((x,i)=><div key={x[0]}><span>{x[0]}</span><i/><p>{x[1]}</p>{i>3&&i<7&&<small>{found.includes(i===6?'C7':'C6')?'证据已确认':'待证实'}</small>}</div>)}</div>}{tab==='证词'&&<div className="testimony-list">{suspects.map((s,i)=><article key={s.name}><span>{s.name} · 初次询问</span><p>“{s.line}”</p><small>{i===0&&found.includes('C9')?'与鞋底痕迹存在矛盾':'证词已记录'}</small></article>)}</div>}{tab==='推论'&&<div className="deduction-list">{deductions.map(d=><article key={d.id} className={solved.has(d.id)?'solved':''}><span>{d.id} / DEDUCTION</span><b>{d.title}</b><p>{solved.has(d.id)?d.body:'未解锁 · 组合对应线索后生成推论'}</p></article>)}</div>}</div><div className="modal-footer"><span><FileText size={14}/> 鹿鸣山庄 · 档案记录</span><span>{found.length} 条线索已归档</span></div></section></div>}

    {modal==='board'&&<div className="overlay board-overlay"><section className="board-modal"><div className="modal-head"><div><span className="eyebrow"><span/> DEDUCTION WALL · LANDSCAPE</span><h2>推理板 <small>把线索放在一起，看看它们说了什么。</small></h2></div><button className="close-x" onClick={()=>setModal('')}><X size={18}/></button></div><div className="board-layout"><div className="board-questions"><span className="board-label">待回答的问题</span>{deductions.map((d,i)=><button className={solved.has(d.id)?'complete':''} key={d.id} onClick={()=>selected!==d.id?setSelected({id:d.id}):setSelected(null)}><span>0{i+1}</span><div><b>{questions[i]}</b><small>{solved.has(d.id)?'推论已成立':`需要 ${d.need.length} 条相互印证的线索`}</small></div>{solved.has(d.id)?<Check size={15}/>:<ArrowRight size={15}/>}</button>)}</div><div className="board-work"><div className="board-work-head"><span>{selected?.id&&deductions.find(d=>d.id===selected.id)?questions[deductions.findIndex(d=>d.id===selected.id)]:'选择一张问题卡，开始拼合线索'}</span><span>{solved.size} / 5 已成立</span></div><div className="chip-cloud">{[...clues.filter(c=>found.includes(c.id)),...deductions.filter(d=>solved.has(d.id))].map(c=><button key={c.id} className={c.key?'key-chip':''} onClick={()=>setSelected(v=>({...v,chip:c.id}))}><i>{c.id}</i>{c.name}</button>)}{!found.length&&<p>完成现场调查后，线索会出现在这里。</p>}</div><div className="board-drop"><div className="drop-emblem"><Fingerprint size={26}/></div><p>{selected?.id&&deductions.find(d=>d.id===selected.id)?'将问题所需的线索组合起来':'选择左侧的问题卡，然后选中线索'}</p><div className="selected-chips">{selected?.picked?.map(x=><button key={x} onClick={()=>setSelected(v=>({...v,picked:v.picked.filter(id=>id!==x)}))}>{clueById(x)?.name}<X size={12}/></button>)}</div>{selected?.chip&&<button className="add-chip" onClick={()=>setSelected(v=>({...v,chip:null,picked:[...new Set([...(v.picked||[]),v.chip])]}))}>加入「{clueById(selected.chip)?.name}」 <ArrowRight size={13}/></button>}<div className="drop-actions"><button onClick={()=>setSelected(null)}>清空</button><button className="primary-btn" disabled={!selected?.id||!deductions.some(d=>d.id===selected.id)||!selected?.picked?.length} onClick={()=>{const d=deductions.find(x=>x.id===selected.id);if(d.need.every(x=>selected.picked.includes(x))){buildDeduction(d);setSelected(null);}else{setCred(v=>Math.max(0,v-2));setToast('这些线索尚不能回答问题 · 可信度 −2');}}}>验证组合 <Check size={14}/></button></div></div><div className="board-hint"><CircleHelp size={14}/><span>所有问题至少需要两条线索。前置推论可作为后续问题的线索。</span><button onClick={()=>{if(intuition>=2){setIntuition(v=>v-2);const d=deductions.find(x=>x.id===selected?.id);setToast(d?`直觉提示：留意「${d.need.map(id=>clueById(id)?.name).join('」与「')}」之间的联系。`:'先选择一张问题卡，再查看提示。');}else setToast('直觉点不足。');}}>直觉提示 · {intuition}</button></div></div></div><div className="modal-footer"><span><Fingerprint size={14}/> 关键推论是结案陈词的入场凭证</span><span>可信度 {cred}</span></div></section></div>}

    {modal==='interview'&&<div className="overlay" onClick={()=>setModal('')}><section className="interview-modal" onClick={e=>e.stopPropagation()}><button className="close-x" onClick={()=>setModal('')}><X size={18}/></button><div className="interview-person"><div className="npc-portrait">{suspects[npc].name[0]}</div><span className="eyebrow"><span/> PERSON OF INTEREST · 0{npc+1}</span><h2>{suspects[npc].name}</h2><p>{suspects[npc].role}</p><div className="attitude"><i/> {challenged?'证词动摇':'态度 · 克制'}</div></div><div className="interview-dialog"><span>当前证词</span><blockquote>“{suspects[npc].line}”</blockquote><div className="dialog-rule"/><p>{challenged?challengeText:suspects[npc].truth}</p>{!challenged&&<div className="topics"><span>可询问话题</span><button>案发经过 <ArrowRight size={13}/></button><button>案发时间 <ArrowRight size={13}/></button><button>与死者的关系 <ArrowRight size={13}/></button></div>}<div className="interview-actions"><button onClick={()=>{setChallenged(v=>!v);setChallengeText('');}}>翻阅证词</button><button className="primary-btn" onClick={()=>{if(npc===0&&!found.includes('C9'))setToast('出示证据需要先调查高坤的鞋底。');else if(npc===3&&!found.includes('C6'))setToast('找到书桌上的手机语音，再回来对峙。');else cross();}}>出示证据 <ArrowRight size={14}/></button></div>{challenged&&<div className="evidence-pick">{clues.filter(c=>found.includes(c.id)).map(c=><button key={c.id} onClick={()=>{if((npc===0&&['C9','C8','C3'].includes(c.id))||(npc===3&&c.id==='C6'))cross();else{setCred(v=>Math.max(0,v-10));setToast('这条证据与证词的矛盾无关 · 可信度 −10');}}}><i>{c.id}</i>{c.name}</button>)}</div>}</div></section></div>}

    {modal==='settings'&&<div className="overlay" onClick={()=>setModal('')}><section className="settings-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow"><span/> ACCESSIBILITY</span><h2>调查设置</h2></div><button className="close-x" onClick={()=>setModal('')}><X size={18}/></button></div><label><span><Eye size={17}/><span><b>热点高亮</b><small>调查时常驻显示尚未查看的热点</small></span></span><input type="checkbox" checked={settings.highlight} onChange={e=>setSettings(v=>({...v,highlight:e.target.checked}))}/></label><label><span><BookOpen size={17}/><span><b>大字号</b><small>提高正文与线索描述的字号</small></span></span><input type="checkbox" checked={settings.largeText} onChange={e=>setSettings(v=>({...v,largeText:e.target.checked}))}/></label><div className="settings-note"><Moon size={15}/> 进度将自动保存在此设备。离线游玩，不需要网络连接。</div></section></div>}
    {modal==='compare'&&<div className="overlay" onClick={()=>setModal('')}><section className="settings-modal" onClick={e=>e.stopPropagation()}><button className="close-x" onClick={()=>setModal('')}><X size={18}/></button><span className="eyebrow"><span/> EVIDENCE COMPARISON</span><h2>线索比对</h2><p>选择两件已归档的线索，检查它们之间的联系。</p><div className="clue-list">{clues.filter(c=>found.includes(c.id)).map(c=><button key={c.id} onClick={()=>setToast(`已将「${c.name}」加入比对。试着在推理板上寻找对应问题。`)}><span>{c.icon}</span><div><b>{c.name}</b><small>{c.id}</small></div><ArrowRight size={14}/></button>)}</div></section></div>}
    {toast&&<div className="toast"><Sparkles size={15}/>{toast}</div>}
  </main>
}

createRoot(document.getElementById('root')).render(<App/>);
